# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir A:/Desktop/Github/CPU/MIPS/MIPS.cache/wt [current_project]
set_property parent.project_path A:/Desktop/Github/CPU/MIPS/MIPS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
read_verilog -library xil_defaultlib {
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/ALUoperations.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/ControlDecoder.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/ALUDecoder.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/ALU.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/MUX.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/ProgramCounter.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/Control.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/signextend.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/RegisterFile.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/InstructionMemory.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/DataMemory.v
  A:/Desktop/Github/CPU/MIPS/MIPS.srcs/sources_1/new/MIPS.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top MIPS -part xc7z020clg484-1


write_checkpoint -force -noxdef MIPS.dcp

catch { report_utilization -file MIPS_utilization_synth.rpt -pb MIPS_utilization_synth.pb }
